services:
  whisper:
    build: .
    container_name: whisper-jp
    volumes:
      - ./src:/app/src
      - ./data/audio:/app/data/audio
      - ./data/output:/app/data/output
      - ${XDG_RUNTIME_DIR}/pipewire-0:/run/user/1000/pipewire-0
      - ${XDG_RUNTIME_DIR}/pulse:/run/user/1000/pulse
    group_add:
      - audio
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - PIPEWIRE_RUNTIME_DIR=/run/user/1000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]