services:
  whisper:
    build: .
    container_name: whisper-jp
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - WHISPER_LANG=${WHISPER_LANG:-ja}
      - WHISPER_MODE=${WHISPER_MODE:-file}
      - PIPEWIRE_RUNTIME_DIR=/run/user/1000
      - XDG_RUNTIME_DIR=/run/user/1000
    volumes:
      - ./src:/app/src
      - ./data/audio:/app/data/audio
      - ./data/output:/app/data/output
      - ${XDG_RUNTIME_DIR}/pipewire-0:/run/user/1000/pipewire-0
      - ${XDG_RUNTIME_DIR}/pipewire:/run/user/1000/pipewire
    group_add:
      - audio
    devices:
      - /dev/snd:/dev/snd
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu,compute,utility]